[build-system]
# AVOID CHANGING REQUIRES: IT WILL BE UPDATED BY PYSCAFFOLD!
requires = ["setuptools>=46.1.0"]
build-backend = "setuptools.build_meta"

[project.urls]
"Homepage" = "https://github.com/luizoti/sheets_factory"
"Bug Tracker" = "https://github.com/luizoti/sheets_factory/issues"
